### ISSUE TITLE
项目安装依赖失败

### ISSUE THREAD

**Issue by jiangxiaoyu66** [lenvo222/imoocmanager#4]
![image](https://user-images.githubusercontent.com/32289005/64682899-e2748680-d4b4-11e9-8c34-d8808f9433d0.png)
在查看资料后，试过用管理员，试过清楚缓存，均未找到解决办法，望解答！！

**Comment by jiangxiaoyu66** [comment]
报错内容如下
`
npm ERR! path C:\git codeBase\node_modules\.staging\antd-b5b31f90\dist\antd.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\git codeBase\node_modules\.staging\antd-b5b31f90\dist\antd.js'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\git codeBase\node_modules\.staging\antd-b5b31f90\dist\antd.js']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\git codeBase\node_modules\.staging\antd-b5b31f90\dist\antd.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\git codeBase\\node_modules\\.staging\\antd-b5b31f90\\dist\\antd.js' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\git codeBase\\node_modules\\.staging\\antd-b5b31f90\\dist\\antd.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\git codeBase\\node_modules\\.staging\\antd-b5b31f90\\dist\\antd.js',
npm ERR!   parent: 'imoocmanager' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-09-11T08_51_15_639Z-debug.log

`

**Comment by lenvo222** [comment]
> ![image](https://user-images.githubusercontent.com/32289005/64682899-e2748680-d4b4-11e9-8c34-d8808f9433d0.png)
> 在查看资料后，试过用管理员，试过清楚缓存，均未找到解决办法，望解答！！
好的, 我试下

**Comment by lenvo222** [comment]
1. 使用 yarn add install 安装依赖库
2. npm start  运行项目
![111](https://user-images.githubusercontent.com/39437437/68653781-6b687680-0567-11ea-8150-e26f71b930f1.jpg)
