### ISSUE TITLE
Child compilation failed

### ISSUE THREAD

**Issue by LxxHub** [lenvo222/imoocmanager#5]

**Comment by LxxHub** [comment]
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed (from ./node_modules/html-webpack-plugin/lib/loader.js):
  Error: ENOENT: no such file or directory, open '/mnt/d/code/react/my-app/public/index.html':
  Error: ENOENT: no such file or directory, open '/mnt/d/code/react/my-app/public/index.html'
  
  - compiler.js:141 childCompiler.runAsChild
    [my-app]/[html-webpack-plugin]/lib/compiler.js:141:18
  
  - Compiler.js:343 compile
    [my-app]/[webpack]/lib/Compiler.js:343:11
  
  - Compiler.js:681 hooks.afterCompile.callAsync.err
    [my-app]/[webpack]/lib/Compiler.js:681:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [my-app]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:678 compilation.seal.err
    [my-app]/[webpack]/lib/Compiler.js:678:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [my-app]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1423 hooks.optimizeAssets.callAsync.err
    [my-app]/[webpack]/lib/Compilation.js:1423:35
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [my-app]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1414 hooks.optimizeChunkAssets.callAsync.err
    [my-app]/[webpack]/lib/Compilation.js:1414:32
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [my-app]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1409 hooks.additionalAssets.callAsync.err
    [my-app]/[webpack]/lib/Compilation.js:1409:36

**Comment by lenvo222** [comment]
[](https://github.com/lenvo222/imoocmanager/issues/4)
https://github.com/lenvo222/imoocmanager/issues/4

**Comment by lenvo222** [comment]
参考:   https://github.com/lenvo222/imoocmanager/issues/4
